# 101 Pandas Exercises for Data Analysis

*by Selva Prabhakaran*

From the website: https://www.machinelearningplus.com/python/101-pandas-exercises-python/

*101 python pandas exercises are designed to challenge your logical muscle and to help internalize data manipulation with python’s favorite package for data analysis.*
*The questions are of 3 levels of difficulties with L1 being the easiest to L3 being the hardest.*

**NOTE**: Again, its 75 not 100, but the exercises are good.

In [ ]:
pip install pandas

1. (L1) **Import `pandas` and check the version**

In [ ]:
import pandas as pd

pd.__version__

2. (L1) **Create a `pandas` series from each of the items below: a list, numpy and a dictionary**

In [ ]:
import numpy as np

# Inputs

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

for data in [mylist, myarr, mydict]:
    print(pd.Series(data).head())

3. (L1) **Convert the series `ser` into a dataframe with its index as another column on the dataframe.**

In [ ]:
# Inputs

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

ser.to_frame().reset_index()

4. (L1) **Combine `ser1` and `ser2` to form a dataframe.**

In [ ]:
# Inputs

ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

np.all(
    pd.DataFrame([ser1, ser2]).T  # Stacking horizontally and rotating by 90 deg
    == pd.concat([ser1, ser2], axis=1)  # Stacking rotated series
)

5. (L1) **Give a name to the series `ser` calling it `my_series`.**

In [ ]:
# Input

ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

ser.name = "my_series"

ser.head()

6. (L2) **From `ser1` remove items present in `ser2`.**

In [ ]:
# Inputs

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# With numpy
with_numpy = np.setdiff1d(ser1, ser2)

# With pandas
with_pandas = ser1[~ser1.isin(ser2)]

print(with_numpy)  # Results in ndarray
print(with_pandas)  # Results in Series

7. (L2) **Get the items not common to both series `ser1` and `ser2`.**

In [ ]:
# Input

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

union = np.union1d(ser1, ser2)
intersection = np.intersect1d(ser1, ser2)

print(union, intersection)
union[~pd.Series(union).isin(intersection)]

8. (L2) **Compute the minimum, 25th percentile, median, 75th, and maximum of `ser`.**

In [ ]:
# Input

ser = pd.Series(np.random.normal(10, 5, 25))

for method in [pd.Series.max, pd.Series.min, pd.Series.median]:
    print(method(ser))
print(ser.quantile(0.25))
print(ser.quantile(0.75))


9. (L2) **Calcualte the frequency counts of each unique item in `ser`.**

In [ ]:
# Input

ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

# Through numpy
with_numpy = np.unique(ser.to_numpy(), return_counts=True)

# Through pandas
with_pandas = ser.value_counts()

print(with_numpy)
print(with_pandas)

10. (L2) **From `ser`, keep the top 2 most frequent items as it is and replace everything else as `Other`.**

In [ ]:
# Input

np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))


ser[~ser.isin(ser.value_counts()[:2].index.to_series())] = 'Other'
print(ser)

11. (L2) **Bin the series `ser` into 10 equal deciles and replace the values with the bin name.**

In [ ]:
# Input

ser = pd.Series(np.random.random(20))

with_cut = pd.cut(
    ser,
    bins=np.percentile(ser, np.arange(0, 110, 10)),
    labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'],
    include_lowest=True
)

with_qcut = pd.qcut(
    ser,
    q=np.arange(0, 1.1, .1),
    labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']
)

np.all(with_cut == with_qcut)

12. (L1) **Reshape the series `ser` into a dataframe with 7 rows and 5 columns.**

In [ ]:
# Input

ser = pd.Series(np.random.randint(1, 10, 35))

pd.DataFrame(
    ser.to_numpy().reshape((7,5))
)

13. (L2)  **Find the positions of numbers that are multiples of 3 from `ser`.**

In [ ]:
# Input

ser = pd.Series(np.random.randint(1, 10, 7))

print(ser)
np.argwhere(ser.to_numpy() % 3 == 0)

14. (L1) **From `ser`, extract the items at positions in list `pos`.**

In [ ]:
# Input

ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

np.all(ser[pos] == ser.take(pos))

15. (L1) **Stack two series vertically and horizontally.**

In [ ]:
# Input

ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

horizontally = pd.concat([ser1, ser2], axis=0)
vertically = pd.concat([ser1, ser2], axis=1)
print(horizontally, vertically)

16. (L2) **Get the positions of items of `ser2` in `ser1` as a list.**

In [ ]:
# Input

ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

np.argwhere(
    ser1.isin(ser2).to_numpy()
)

17. (L2) **Compute the mean squared error of `truth` and `pred`.**

**NOTE**: This question means that we need to calculate the mean squared error between the two series, using the formula:

$$MSE = \dfrac{1}{n} * \sum \left(truth - pred\right)^2$$

In [ ]:
# Input

truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

np.mean(
    (truth-pred)**2  # Squares of errors
)

18. (L2) **Convert the first character of each element in `ser` to uppercase.**

In [ ]:
# Input

ser = pd.Series(['how', 'to', 'kick', 'ass?'])

ser.apply(str.title)

19. (L2) **Calculate the number of characters in each word in `ser`.**

In [ ]:
# Input

ser = pd.Series(['how', 'to', 'kick', 'ass?'])

ser.apply(len)

20. (L2) **Compute the difference of differences between consecutive numbers in `ser`.**

In [ ]:
# Input

ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

ser.diff().diff()

21. (L2) **Convert a series of date-strings to a timeseries**

Desired output:

```
0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]
```

In [ ]:
# Input

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

ser.astype('datetime64[ns]')

22. (L2) **Get the day of month, week number, day of year and day of week from `ser`.**

Desired output:

```
Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']
```

In [ ]:
# Input

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Manual

dates = []
week_numbers = []
day_numbers = []
weekdays = []
weekday_names = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Friday']

for index, date in enumerate(ser.astype('datetime64[ns]')):
    dates.append(index)
    week_numbers.append(date.week)
    day_numbers.append(date.day_of_year)
    weekdays.append(weekday_names[date.weekday()])

print('Manual')
print(dates)
print(week_numbers)
print(day_numbers)
print(weekdays)

# With 'dt' property (incomplete)

import dateutil

timeseries = ser.map(dateutil.parser.parse)

print('\nThrough API')
print(timeseries.dt.day.to_list())
#print(timeseries.dt.weekofyear.to_list()) Doesn't work anymore, maybe API changed!
print(timeseries.dt.day_of_year.to_list())
print(timeseries.dt.weekday.map(lambda weekday_number: weekday_names[weekday_number]).to_list())

23. (L2) **Change `ser` to dates that start with 4th of the respective months.**

In [ ]:
# Input

ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

import datetime
def shift_day(day_string: str) -> datetime.datetime:
    return dateutil.parser.parse(f'4th {day_string}')

pd.Series(
    np.vectorize(shift_day)(ser)
)

24. (L3) **From `ser`, extract words that contain atleast 2 vowels.**

In [ ]:
# Input

ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

def count_vowels(word: str) -> int:
    return len([
        letter
        for letter in np.array([*word.lower()])
        if letter in ['a', 'e', 'i', 'o', 'u']
    ])

ser[
    ser.map(count_vowels) >= 2  # This serves as mask for the ser Series
]

25. (L3) **Extract the valid `emails` from the series emails. The regex pattern for valid emails is provided as reference.**

In [ ]:
# Input

emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

import re

emails[
    emails.map(
        lambda input_email: re.compile(pattern).match(input_email)
    ).values != None
]

26. (L2) **Compute the mean of `weights` of each `fruit`.**

In [ ]:
# Inputs

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

fruits_dataframe = pd.DataFrame(
    np.vstack([fruit, weights])
).T
fruits_dataframe.columns = ["fruit", "weight"]
fruits_dataframe.groupby('fruit').mean()

27. (L2) **Compute the euclidean distance between series (points) p and q, without using a packaged formula.**

In [ ]:
# Inputs

p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

via_dataframe = np.sqrt(
    pd.DataFrame([p,q]).T.apply(lambda row: (row[1]-row[0])**2, axis=1).sum(axis=0)
)
via_norm = np.sqrt(np.sum((q-p)**2))

np.isclose(via_dataframe, via_norm)

28. (L3) **Get the positions of peaks (values surrounded by smaller values on both sides) in `ser`.**

In [ ]:
# Input

ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

# From NumPy exercises
a_diffs = np.sign(np.diff(np.hstack([ser[0], ser])))
[
    diff_index
    for diff_index in range(len(a_diffs[1:]))
    if a_diffs[diff_index] == 1 and a_diffs[diff_index+1] == -1  # Signs of differences: (+1) / [MAX] \ (-1)
]

29. (L3) **Replace missing spaces in the string `my_str` with the least frequent character.**

In [ ]:
# Input

my_str = 'dbc deb abed gade'

uniques, counts = np.unique(
    pd.Series([*my_str]),
    return_counts=True
)
least_frequent_character = uniques[np.argmin(counts)]

my_str.replace(' ', least_frequent_character)

30. (L3) **Create a TimeSeries starting `2000-01-01` and 10 weekends (saturdays) after that having random numbers as values.**

In [ ]:
pd.DataFrame({
    'date': pd.date_range('2020-01-01', periods=10, freq='7D'),
    'number': np.random.randint(low=0, high=100, size=10)
})

31. (L2) **`ser` has missing dates and values. Make all missing dates appear and fill up with value from previous date.**


In [ ]:
# Input

ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

'''
From docs:

Series.resample: method for frequency conversion and resampling of time series

Here: instead of sampling at random days, we shift the frequency to ONE DAY and then fill missing values with ffill
'''
ser.resample('D').ffill()

32. (L3) **Compute autocorrelations for the first 10 lags of `ser`. Find out which lag has the largest correlation.**

Desired output:

```python
# values will change due to randomness
[0.29999999999999999, -0.11, -0.17000000000000001, 0.46000000000000002, 0.28000000000000003, -0.040000000000000001, -0.37, 0.41999999999999998, 0.47999999999999998, 0.17999999999999999]
Lag having highest correlation:  9
```

In [ ]:
# Input

ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

autocorrelations = pd.Series([
    ser.autocorr(lag)
    for lag in range(1,11)
])

print(autocorrelations.to_list())
print(autocorrelations.copy().abs().argmax() + 1)

33. (L2) **Import every 50th row of `boston` dataset as a dataframe.**

In [ ]:
import requests

BOSTON_URL = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"

pd.DataFrame([
    chunk.iloc[0,:]  # This takes first line
    for chunk in pd.read_csv(
        BOSTON_URL,
        chunksize=50  # Of every chunk that is 50 rows long
    )
]).reset_index().drop('index', axis=1)

34. (L2) **Import the boston housing dataset, but while importing change the `medv` (median house value) column so that values < 25 becomes `Low` and > 25 becomes `High`.**

In [ ]:
def categorize(row: np.generic):
    row['medv'] = 'Low' if row['medv'] < 25 else 'High'
    return row

via_apply = pd.read_csv(BOSTON_URL).apply(categorize, axis=1)
via_converters = pd.read_csv(BOSTON_URL, converters={
    'medv': lambda median_value: 'Low' if float(median_value) < 25 else 'High'
})
np.all(via_apply == via_converters)

35. (L3) **Create a dataframe with rows as strides from a given series**

Desired output:

```python
array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])
```

In [ ]:
# Input

L = pd.Series(range(15))

window_width = 4
stride_jump = 2

pd.DataFrame(
np.array(
    [
        L[stride_jump*stride:(stride_jump*stride+window_width)]
        for stride in range(int((len(L)-window_width)/stride_jump) + 1)
    ]
    ).reshape(
        (-1, window_width)
    )
)

36. (L1) **Import `crim` and `medv` columns of the BostonHousing dataset as a dataframe.**

In [ ]:
pd.read_csv(BOSTON_URL, usecols=['crim', 'medv'])

37. (L2) **Get the number of rows, columns, datatype and summary statistics of each column of the `Cars93` dataset. Also get the numpy array and list equivalent of the dataframe.**

In [ ]:
# Input

CARS93_URL = "https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv"
cars = pd.read_csv(CARS93_URL)

print(
    cars.info(),
    '\n',
    cars.describe(),
    '\n',
    cars.to_numpy(),
    '\n',
    cars.to_numpy().tolist()
)

38. (L1) **Which manufacturer, model and type has the highest Price? What is the row and column number of the cell with the highest Price value?**

In [ ]:
# Input

cars = pd.read_csv(CARS93_URL)

max_price_car = cars.loc[
    np.argmax(  # Row of max price
        cars['Price']
    ), 
    ['Manufacturer', 'Model', 'Type']  # Which columns
]
print(max_price_car)
np.where(  # Locate i,j of max Price cell
    cars.values == np.max(cars['Price'])
)

39. (L2) **Rename the column `Type` as `CarType` in df and replace the `.` in column names with `_`.**

Desired output:

```python
 print(df.columns)
#> Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
#>        'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
#>        'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')
```

In [ ]:
# Input

cars = pd.read_csv(CARS93_URL)

cars.columns = [
    column.replace('.', '_')
    for column in cars.columns
]
cars.rename(columns={'Type': 'CarType'})

40. (L1) **Check if `df` has any missing values.**

In [ ]:
# Input

cars = pd.read_csv(CARS93_URL)

np.any(
    cars.isna()
)

41. (L2) **Count the number of missing values in each column of `df`.**

In [ ]:
# Input

cars = pd.read_csv(CARS93_URL)

nans = cars.isna().astype(int).sum(axis=0)
nans[
    nans == nans.max()
]

42. (L2) **Replace missing values in `Min.Price` and `Max.Price` columns with their respective mean.**

In [ ]:
# Input

cars = pd.read_csv(CARS93_URL)

for column in ['Min.Price', 'Max.Price']:
    cars[column].fillna(
        cars[column].mean().round(1),
        inplace=True
    )
cars

43. (L3) **In `df`, use apply method to replace the missing values in `Min.Price` with the column’s mean and those in `Max.Price` with the column’s median.**

In [ ]:
# Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

def filler(column: pd.Series):  # On deafult, apply happens PER COLUMN
    if reducer := {
        'Min.Price': np.nanmean,  # Drops NaN
        'Max.Price': np.nanmedian,  # Ditto
    }.get(column.name):
        return column.fillna(value=reducer(column).round(1))
    return column

df.apply(filler)

44. (L2) **Get the first column (a) in `df` as a dataframe (rather than as a series).**

In [252]:
# Input

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

np.all(
    pd.DataFrame(df[  # Brute-force
        df.columns[0]
    ]) == df[[df.columns[0]]]  # Shorthand
)

True

45. (L3) Actually 3 questions.

* **In `df`, interchange columns `a` and `c`.**
* **Create a generic function to interchange two columns, without hardcoding column names.**
* **Sort the columns in reverse alphabetical order, that is column `e` first through column `a` last.**

In [292]:
# Input

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Swapping function
def swap_axes(dataframe: pd.DataFrame, axis_1: str, axis_2: str) -> None:
    if axis_1 == axis_2:
        return
    dataframe[[axis_1, axis_2]] = df[[axis_2, axis_1]]
    dataframe.rename(mapper={axis_1: axis_2, axis_2: axis_1}, inplace=True, axis=1)

# Reversing with the function
for mapping_index in range(len(df.columns)):
    axis_1 = df.columns[mapping_index] 
    axis_2 = sorted(df.columns, reverse=True)[mapping_index]
    swap_axes(df, axis_1=axis_1, axis_2=axis_2)

print(df)

# Sorting alphabetically, descending
df.sort_index(axis=1, ascending=False, inplace=True)
df

    e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15


e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

46. (L2) **Change the pandas display settings on printing the dataframe `df` it shows a maximum of 10 rows and 10 columns.**

In [296]:
# Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 10)
df


Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small       12.9   15.9  ...            26.5   
1           NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2          Audi       90  Compact       25.9   29.1  ...            28.0   
3          Audi      100  Midsize        NaN   37.7  ...            31.0   
4           BMW     535i  Midsize        NaN   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van       16.6   19.7  ...            34.0   
89   Volkswagen   Passat  Compact       17.6   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty       22.9   23.3  ...            26.0   
91        Volvo      240  Compact       21.8   22.7  ...            29.5   
92          NaN      850  Midsize       24.8   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-USA       Acura Integra  
1           15.0  3560.0  non-USA        Acura Legend  
2           14.0  3375.0  non-USA             Audi 90  
3           17.0  3405.0  non-USA            Audi 100  
4           13.0  3640.0  non-USA            BMW 535i  
..           ...     ...      ...                 ...  
88           NaN  3960.0      NaN  Volkswagen Eurovan  
89          14.0  2985.0  non-USA   Volkswagen Passat  
90          15.0  2810.0  non-USA  Volkswagen Corrado  
91          14.0  2985.0  non-USA           Volvo 240  
92          15.0  3245.0  non-USA           Volvo 850  

[93 rows x 27 columns]

47. (L2) **Suppress scientific notations like `e-03` in df and print upto 4 numbers after decimal.**

Desired output:

```python
#>    random
#> 0  0.0035
#> 1  0.0000
#> 2  0.0747
#> 3  0.0000
```

In [299]:
# Input

df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

pd.set_option('display.precision', 4)
df

random
0  0.1243
1  0.0002
2  0.0897
3  0.8119

48. (L2) **Format the values in column `random` of `df` as percentages.**

In [304]:
# Input

df = pd.DataFrame(np.random.random(4), columns=['random'])

df.style.format({
    'random': lambda value: f'{round((value * 100), 2)}%'
})

49. (L1) **From `df`, filter the `Manufacturer`, `Model` and `Type` for every 20th row starting from 1st (row 0).**

In [306]:
# Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df[['Manufacturer', 'Model', 'Type']].iloc[::20]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

50. (L2) **In `df`, Replace NaNs with ‘missing’ in columns 'Manufacturer', 'Model' and 'Type' and create a index as a combination of these three columns and check if the index is a primary key.**

Desired output:

```python
                       Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small           Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize      missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                Audi       90  Compact       25.9       32.3
Audi_100_Midsize               Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                BMW     535i  Midsize        NaN        NaN
```

In [332]:
# Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna(value='missing')
df.set_index(
    df['Manufacturer'] + '_' + df['Model'] + '_' + df['Type']
)

Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small              Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize         missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                   Audi       90  Compact       25.9       32.3
Audi_100_Midsize                  Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                   BMW     535i  Midsize        NaN        NaN
...                                ...      ...      ...        ...        ...
Volkswagen_Eurovan_Van      Volkswagen  Eurovan      Van       16.6       22.7
Volkswagen_Passat_Compact   Volkswagen   Passat  Compact       17.6       22.4
Volkswagen_Corrado_Sporty   Volkswagen  Corrado   Sporty       22.9       23.7
Volvo_240_Compact                Volvo      240  Compact       21.8       23.5
missing_850_Midsize            missing      850  Midsize       24.8       28.5

[93 rows x 5 columns]